# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/hemanthharidas/Desktop/codes/cpp_projects/hartee-fock-v2

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/hemanthharidas/Desktop/codes/cpp_projects/hartee-fock-v2

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/opt/homebrew/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/opt/homebrew/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/hemanthharidas/Desktop/codes/cpp_projects/hartee-fock-v2/CMakeFiles /Users/hemanthharidas/Desktop/codes/cpp_projects/hartee-fock-v2//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/hemanthharidas/Desktop/codes/cpp_projects/hartee-fock-v2/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named hartree-fock

# Build rule for target.
hartree-fock: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 hartree-fock
.PHONY : hartree-fock

# fast build rule for target.
hartree-fock/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hartree-fock.dir/build.make CMakeFiles/hartree-fock.dir/build
.PHONY : hartree-fock/fast

#=============================================================================
# Target rules for targets named libmsym

# Build rule for target.
libmsym: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 libmsym
.PHONY : libmsym

# fast build rule for target.
libmsym/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libmsym.dir/build.make CMakeFiles/libmsym.dir/build
.PHONY : libmsym/fast

hartree-fock.o: hartree-fock.cpp.o
.PHONY : hartree-fock.o

# target to build an object file
hartree-fock.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hartree-fock.dir/build.make CMakeFiles/hartree-fock.dir/hartree-fock.cpp.o
.PHONY : hartree-fock.cpp.o

hartree-fock.i: hartree-fock.cpp.i
.PHONY : hartree-fock.i

# target to preprocess a source file
hartree-fock.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hartree-fock.dir/build.make CMakeFiles/hartree-fock.dir/hartree-fock.cpp.i
.PHONY : hartree-fock.cpp.i

hartree-fock.s: hartree-fock.cpp.s
.PHONY : hartree-fock.s

# target to generate assembly for a file
hartree-fock.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hartree-fock.dir/build.make CMakeFiles/hartree-fock.dir/hartree-fock.cpp.s
.PHONY : hartree-fock.cpp.s

src/basis/basis.o: src/basis/basis.cpp.o
.PHONY : src/basis/basis.o

# target to build an object file
src/basis/basis.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hartree-fock.dir/build.make CMakeFiles/hartree-fock.dir/src/basis/basis.cpp.o
.PHONY : src/basis/basis.cpp.o

src/basis/basis.i: src/basis/basis.cpp.i
.PHONY : src/basis/basis.i

# target to preprocess a source file
src/basis/basis.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hartree-fock.dir/build.make CMakeFiles/hartree-fock.dir/src/basis/basis.cpp.i
.PHONY : src/basis/basis.cpp.i

src/basis/basis.s: src/basis/basis.cpp.s
.PHONY : src/basis/basis.s

# target to generate assembly for a file
src/basis/basis.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hartree-fock.dir/build.make CMakeFiles/hartree-fock.dir/src/basis/basis.cpp.s
.PHONY : src/basis/basis.cpp.s

src/basis/gaussian.o: src/basis/gaussian.cpp.o
.PHONY : src/basis/gaussian.o

# target to build an object file
src/basis/gaussian.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hartree-fock.dir/build.make CMakeFiles/hartree-fock.dir/src/basis/gaussian.cpp.o
.PHONY : src/basis/gaussian.cpp.o

src/basis/gaussian.i: src/basis/gaussian.cpp.i
.PHONY : src/basis/gaussian.i

# target to preprocess a source file
src/basis/gaussian.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hartree-fock.dir/build.make CMakeFiles/hartree-fock.dir/src/basis/gaussian.cpp.i
.PHONY : src/basis/gaussian.cpp.i

src/basis/gaussian.s: src/basis/gaussian.cpp.s
.PHONY : src/basis/gaussian.s

# target to generate assembly for a file
src/basis/gaussian.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hartree-fock.dir/build.make CMakeFiles/hartree-fock.dir/src/basis/gaussian.cpp.s
.PHONY : src/basis/gaussian.cpp.s

src/integrals/base.o: src/integrals/base.cpp.o
.PHONY : src/integrals/base.o

# target to build an object file
src/integrals/base.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hartree-fock.dir/build.make CMakeFiles/hartree-fock.dir/src/integrals/base.cpp.o
.PHONY : src/integrals/base.cpp.o

src/integrals/base.i: src/integrals/base.cpp.i
.PHONY : src/integrals/base.i

# target to preprocess a source file
src/integrals/base.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hartree-fock.dir/build.make CMakeFiles/hartree-fock.dir/src/integrals/base.cpp.i
.PHONY : src/integrals/base.cpp.i

src/integrals/base.s: src/integrals/base.cpp.s
.PHONY : src/integrals/base.s

# target to generate assembly for a file
src/integrals/base.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hartree-fock.dir/build.make CMakeFiles/hartree-fock.dir/src/integrals/base.cpp.s
.PHONY : src/integrals/base.cpp.s

src/io/io.o: src/io/io.cpp.o
.PHONY : src/io/io.o

# target to build an object file
src/io/io.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hartree-fock.dir/build.make CMakeFiles/hartree-fock.dir/src/io/io.cpp.o
.PHONY : src/io/io.cpp.o

src/io/io.i: src/io/io.cpp.i
.PHONY : src/io/io.i

# target to preprocess a source file
src/io/io.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hartree-fock.dir/build.make CMakeFiles/hartree-fock.dir/src/io/io.cpp.i
.PHONY : src/io/io.cpp.i

src/io/io.s: src/io/io.cpp.s
.PHONY : src/io/io.s

# target to generate assembly for a file
src/io/io.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hartree-fock.dir/build.make CMakeFiles/hartree-fock.dir/src/io/io.cpp.s
.PHONY : src/io/io.cpp.s

src/io/logging.o: src/io/logging.cpp.o
.PHONY : src/io/logging.o

# target to build an object file
src/io/logging.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hartree-fock.dir/build.make CMakeFiles/hartree-fock.dir/src/io/logging.cpp.o
.PHONY : src/io/logging.cpp.o

src/io/logging.i: src/io/logging.cpp.i
.PHONY : src/io/logging.i

# target to preprocess a source file
src/io/logging.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hartree-fock.dir/build.make CMakeFiles/hartree-fock.dir/src/io/logging.cpp.i
.PHONY : src/io/logging.cpp.i

src/io/logging.s: src/io/logging.cpp.s
.PHONY : src/io/logging.s

# target to generate assembly for a file
src/io/logging.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hartree-fock.dir/build.make CMakeFiles/hartree-fock.dir/src/io/logging.cpp.s
.PHONY : src/io/logging.cpp.s

src/lookup/elements.o: src/lookup/elements.cpp.o
.PHONY : src/lookup/elements.o

# target to build an object file
src/lookup/elements.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hartree-fock.dir/build.make CMakeFiles/hartree-fock.dir/src/lookup/elements.cpp.o
.PHONY : src/lookup/elements.cpp.o

src/lookup/elements.i: src/lookup/elements.cpp.i
.PHONY : src/lookup/elements.i

# target to preprocess a source file
src/lookup/elements.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hartree-fock.dir/build.make CMakeFiles/hartree-fock.dir/src/lookup/elements.cpp.i
.PHONY : src/lookup/elements.cpp.i

src/lookup/elements.s: src/lookup/elements.cpp.s
.PHONY : src/lookup/elements.s

# target to generate assembly for a file
src/lookup/elements.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hartree-fock.dir/build.make CMakeFiles/hartree-fock.dir/src/lookup/elements.cpp.s
.PHONY : src/lookup/elements.cpp.s

src/symmetry/symmetry.o: src/symmetry/symmetry.cpp.o
.PHONY : src/symmetry/symmetry.o

# target to build an object file
src/symmetry/symmetry.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hartree-fock.dir/build.make CMakeFiles/hartree-fock.dir/src/symmetry/symmetry.cpp.o
.PHONY : src/symmetry/symmetry.cpp.o

src/symmetry/symmetry.i: src/symmetry/symmetry.cpp.i
.PHONY : src/symmetry/symmetry.i

# target to preprocess a source file
src/symmetry/symmetry.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hartree-fock.dir/build.make CMakeFiles/hartree-fock.dir/src/symmetry/symmetry.cpp.i
.PHONY : src/symmetry/symmetry.cpp.i

src/symmetry/symmetry.s: src/symmetry/symmetry.cpp.s
.PHONY : src/symmetry/symmetry.s

# target to generate assembly for a file
src/symmetry/symmetry.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hartree-fock.dir/build.make CMakeFiles/hartree-fock.dir/src/symmetry/symmetry.cpp.s
.PHONY : src/symmetry/symmetry.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... libmsym"
	@echo "... hartree-fock"
	@echo "... hartree-fock.o"
	@echo "... hartree-fock.i"
	@echo "... hartree-fock.s"
	@echo "... src/basis/basis.o"
	@echo "... src/basis/basis.i"
	@echo "... src/basis/basis.s"
	@echo "... src/basis/gaussian.o"
	@echo "... src/basis/gaussian.i"
	@echo "... src/basis/gaussian.s"
	@echo "... src/integrals/base.o"
	@echo "... src/integrals/base.i"
	@echo "... src/integrals/base.s"
	@echo "... src/io/io.o"
	@echo "... src/io/io.i"
	@echo "... src/io/io.s"
	@echo "... src/io/logging.o"
	@echo "... src/io/logging.i"
	@echo "... src/io/logging.s"
	@echo "... src/lookup/elements.o"
	@echo "... src/lookup/elements.i"
	@echo "... src/lookup/elements.s"
	@echo "... src/symmetry/symmetry.o"
	@echo "... src/symmetry/symmetry.i"
	@echo "... src/symmetry/symmetry.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

